class Error:

    CONNECTION_ERROR = 100
    
    SERVER_NOT_FOUND = 150
    SERVER_IS_ALREADY_RUNNING = 151
    SERVER_IS_DISABLED = 152

    CLUSTER_NOT_FOUND = 180
    CLUSTER_IS_ALREADY_RUNNING = 181
